#!/usr/bin/env bash
# ha proxy script

sudo apt-get update
sudo apt-get install -y haproxy
sudo chown -R "$USER":"sudo" /etc/haproxy

CONFIGURATION="\
frontend http
   bind *:80
   mode http
   default_backend mybackends

backend mybackends
   balance roundrobin
   server 134177-web-01 174.129.55.229 check
   server 134177-web-02 54.160.113.203 check
 "
echo -e "$CONFIGURATION" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
